// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvx1va1jQWozWUJtyH-gJGpCkk5uCBWCk',
    appId: '1:462043639167:web:3290fdec4a9e865ec6be4a',
    messagingSenderId: '462043639167',
    projectId: 'oyunbatauthproject',
    authDomain: 'oyunbatauthproject.firebaseapp.com',
    storageBucket: 'oyunbatauthproject.firebasestorage.app',
    measurementId: 'G-2Q079M2LZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLD9z23DNiCXlngjXN-Iw5jRPpK_FY9yY',
    appId: '1:462043639167:android:f4f33246d63b25c9c6be4a',
    messagingSenderId: '462043639167',
    projectId: 'oyunbatauthproject',
    storageBucket: 'oyunbatauthproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQEbA3VU3k_j-1pTzjCg2Vb-RXNOpUes',
    appId: '1:462043639167:ios:a8ad82fa0fbb5c87c6be4a',
    messagingSenderId: '462043639167',
    projectId: 'oyunbatauthproject',
    storageBucket: 'oyunbatauthproject.firebasestorage.app',
    androidClientId: '462043639167-2qgkq0dd3ut3aickijbtp35h0tu0por0.apps.googleusercontent.com',
    iosClientId: '462043639167-fkb4a8ljj51nujsgblntbjpu2duhuomd.apps.googleusercontent.com',
    iosBundleId: 'com.example.productapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQEbA3VU3k_j-1pTzjCg2Vb-RXNOpUes',
    appId: '1:462043639167:ios:a8ad82fa0fbb5c87c6be4a',
    messagingSenderId: '462043639167',
    projectId: 'oyunbatauthproject',
    storageBucket: 'oyunbatauthproject.firebasestorage.app',
    androidClientId: '462043639167-2qgkq0dd3ut3aickijbtp35h0tu0por0.apps.googleusercontent.com',
    iosClientId: '462043639167-fkb4a8ljj51nujsgblntbjpu2duhuomd.apps.googleusercontent.com',
    iosBundleId: 'com.example.productapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvx1va1jQWozWUJtyH-gJGpCkk5uCBWCk',
    appId: '1:462043639167:web:763ca2529ee12436c6be4a',
    messagingSenderId: '462043639167',
    projectId: 'oyunbatauthproject',
    authDomain: 'oyunbatauthproject.firebaseapp.com',
    storageBucket: 'oyunbatauthproject.firebasestorage.app',
    measurementId: 'G-Y5ZKNHS87W',
  );
}
